//! Autogenerated weights for pallet_dapi
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-12, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/massbit-collator
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_dapi
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/dapi/src/weights.rs
// --template
// ./benchmarking/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_dapi.
pub trait WeightInfo {
	#[rustfmt::skip]
	fn register_project() -> Weight;
	#[rustfmt::skip]
	fn deposit_project() -> Weight;
	#[rustfmt::skip]
	fn register_provider() -> Weight;
	#[rustfmt::skip]
	fn unregister_provider() -> Weight;
	#[rustfmt::skip]
	fn add_chain_id() -> Weight;
	#[rustfmt::skip]
	fn remove_chain_id() -> Weight;
	#[rustfmt::skip]
	fn add_regulator() -> Weight;
	#[rustfmt::skip]
	fn remove_regulator() -> Weight;
}

/// Weights for pallet_dapi using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: DapiStaking BlockRewardAccumulator (r:1 w:1)
	#[rustfmt::skip]
	fn register_project() -> Weight {
		(35_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: DapiStaking BlockRewardAccumulator (r:1 w:1)
	#[rustfmt::skip]
	fn deposit_project() -> Weight {
		(28_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: DapiStaking Ledger (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	// Storage: DapiStaking ProviderEraStake (r:1 w:1)
	// Storage: DapiStaking GeneralStakerInfo (r:1 w:1)
	// Storage: DapiStaking GeneralEraInfo (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	#[rustfmt::skip]
	fn register_provider() -> Weight {
		(45_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(10 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	#[rustfmt::skip]
	fn unregister_provider() -> Weight {
		(15_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi ChainIds (r:1 w:1)
	#[rustfmt::skip]
	fn add_chain_id() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi ChainIds (r:1 w:1)
	#[rustfmt::skip]
	fn remove_chain_id() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi Regulators (r:1 w:1)
	#[rustfmt::skip]
	fn add_regulator() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi Regulators (r:1 w:1)
	#[rustfmt::skip]
	fn remove_regulator() -> Weight {
		(10_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: DapiStaking BlockRewardAccumulator (r:1 w:1)
	#[rustfmt::skip]
	fn register_project() -> Weight {
		(35_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: DapiStaking BlockRewardAccumulator (r:1 w:1)
	#[rustfmt::skip]
	fn deposit_project() -> Weight {
		(28_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: DapiStaking Ledger (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	// Storage: DapiStaking ProviderEraStake (r:1 w:1)
	// Storage: DapiStaking GeneralStakerInfo (r:1 w:1)
	// Storage: DapiStaking GeneralEraInfo (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	#[rustfmt::skip]
	fn register_provider() -> Weight {
		(45_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(10 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	#[rustfmt::skip]
	fn unregister_provider() -> Weight {
		(15_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi ChainIds (r:1 w:1)
	#[rustfmt::skip]
	fn add_chain_id() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi ChainIds (r:1 w:1)
	#[rustfmt::skip]
	fn remove_chain_id() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi Regulators (r:1 w:1)
	#[rustfmt::skip]
	fn add_regulator() -> Weight {
		(9_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Dapi Regulators (r:1 w:1)
	#[rustfmt::skip]
	fn remove_regulator() -> Weight {
		(10_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
