[workspace]
members = [
	"node",
	"pallets/block-reward",
	"pallets/dapi",
	"pallets/dapi-staking",
	"pallets/validator-set",
	"runtime/local",
    "runtime/keiko",
]
[profile.release]
panic = "unwind"
